service: serverless-template-nodejs

frameworkVersion: '2'

plugins:
  - serverless-bundle
  - serverless-pseudo-parameters

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'dev'}
  region: ap-south-1

functions:
  hello:
    handler: src/functions/hello.handler
    events:
      - httpApi:
          method: GET
